# Generated by Django 5.0.6 on 2024-06-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggestion',
            new_name='Suggestions',
        ),
    ]
