# Generated by Django 5.0.6 on 2024-06-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_rename_suggestion_suggestions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
