# Generated by Django 5.0.6 on 2024-06-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
