# Generated by Django 5.0.6 on 2024-06-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0002_alter_reclamation_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('acceptee', 'acceptee')], default='en_attente', max_length=10),
        ),
    ]
