# Generated by Django 5.0.6 on 2024-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("factures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="client",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="facture",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="facture",
            name="numero",
            field=models.CharField(max_length=100),
        ),
    ]
