# Generated by Django 5.0.6 on 2024-06-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfertligne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlignes',
            name='numero_de_ligne',
            field=models.IntegerField(),
        ),
    ]
